# File: azure-pipelines.yml
# Build Name / Format
name: PowerAppsTestAutomation-$(date:yyyyMMdd)$(rev:.r)

resources:
  repositories:
    - repository: PowerAppsTestAutomation
      type: github
      # GitHub Repo(e.g. <FORK>/PowerAppsTestAutomation)
      # Recommended to Fork or Duplicate if custom auth flows are required
      name: microsoft/PowerAppsTestAutomation
      ref: master
      # Name of the GitHub OAuth ADO Service Connection
      endpoint: github.com_Anne-French

parameters:
 - name: image
   displayName: Pool Image
   type: string
   # See https://github.com/MicrosoftDocs/azure-devops-docs/blob/master/docs/pipelines/agents/hosted.md#use-a-microsoft-hosted-agent for more pool types
   default: windows-latest
   values:
   - windows-latest
 - name: BrowserType
   displayName: Browser Type
   type: string
   default: Chrome
   values:
   - Chrome
   - Firefox
 - name: LoginMethod
   displayName: Login Type # See: https://docs.microsoft.com/en-us/office365/servicedescriptions/office-365-platform-service-description/user-account-management
   type: string
   default: CloudIdentity
   values:
   - CloudIdentity # Uses the default Office 365 Sign-In Service for authentication

jobs:
- job: "PowerAppsTestFrameworkAutomation"
  pool:
    name: doe  # Use the name of your new self-hosted agent pool here
  steps:
  - checkout: self
  - checkout: PowerAppsTestAutomation
  #- template: localsteps.yml # Provide optional local YAML template here
  - template: frameworksteps.yml@PowerAppsTestAutomation
    parameters:
      OnlineUsername: $(OnlineUsername)
      OnlinePassword: $(OnlinePassword)
      OnlineUrl: https://make.powerapps.com  # Move this definition here if it's used in subsequent steps
      BrowserType: ${{ parameters.BrowserType }}
      # File location format is /s/TeamProjectName/FilePathToTestAutomationURLs.json
      TestAutomationURLFilePath: $(Build.SourcesDirectory)\$(LocalProjectName)\Samples\$(TestUrlFileName)
      UsePrivateMode: true  # Assuming this is a boolean variable
      LoginMethod: ${{ parameters.LoginMethod }}
